### ISSUE TITLE
/cake/Cake: Permission denied

### ISSUE THREAD

**Issue by gitfool** [cake-build/docker#8]
`/cake/Cake` is missing executable permissions. See [Cake.Dungeon Docker Job](https://dev.azure.com/gitfool/Cake.Dungeon/_build/results?buildId=9&view=logs&jobId=1c8ce01e-97de-5be9-a863-648419f09741&taskId=09181c4b-3f3c-50e9-b57f-22616eaa56ea&lineStart=13&lineEnd=14&colStart=1&colEnd=1).

```
~$ docker run --rm -it cakebuild/cake:v0.32.1-2.1-sdk
root@aab27beb84ed:/src# which cake
/cake/cake
root@aab27beb84ed:/src# ls -al /cake/cake
-rwxr-xr-x 1 root root 30 Jan  4 20:43 /cake/cake
root@aab27beb84ed:/src# cat /cake/cake
#!/bin/sh
exec /cake/Cake "$@"
root@aab27beb84ed:/src# ls -al /cake/Cake
-rwxrw-rw- 1 root root 97416 Jan  4 20:42 /cake/Cake
```
PS. Add a trailing newline to `/cake/cake` so `cat` looks clean.

**Comment by devlead** [comment]
Interesting, `cake --info` and `Cake --info` works though. `x` would indicate execute bit is there.

![image](https://user-images.githubusercontent.com/1647294/50730280-edb72b80-1149-11e9-9ba1-f2676713087e.png)

What does your your docker file look like? Or how are you launching the container?

**Comment by gitfool** [comment]
From WSL, via `docker run --rm -it cakebuild/cake:v0.32.1-2.1-sdk`.

From Azure Pipelines, via [Cake.Dungeon/azure-pipelines.yml#L10](https://github.com/gitfool/Cake.Dungeon/blob/master/azure-pipelines.yml#L10), in which I may be missing something as that build is my very first attempt to build with a Docker container on Azure Pipelines.

**Comment by devlead** [comment]
Bit is there for the executing user though 
![image](https://user-images.githubusercontent.com/1647294/50730480-beef8400-114e-11e9-914b-ff8caeb08a7f.png)
Container only has root user.

Other wise neither `cake --info` nor `Cake -info` should work.

With the yaml you link to I would assume the bash build step runs on the VM and not the container.

In general without a Docker file you can only run one command with docker run, a workaround would be something like `docker run --rm -it cakebuild/cake:v0.32.1-2.1-sdk /bin/bash -c "cake --botstrap && cake"`

A yaml step in Azure Pipelines could look something like
```yaml
- task: Docker@1
  displayName: 'Run an image'
  inputs:
    containerregistrytype: 'Container Registry'

    command: 'Run an image'

    imageName: 'cakebuild/cake:v0.32.1-2.1-sdk'

    volumes: '$(Build.Repository.LocalPath):/repository'

    workingDirectory: /repository

    containerCommand: '/bin/bash -c "cake --botstrap && cake"'

    runInBackground: false

```

you could also have a Dockerfile in repo

Then step would look something like 
```yaml
- task: Docker@1
  displayName: 'Build image'
```
And a Dockerfile could look something like

```Dockerfile
FROM cakebuild/cake:v0.32.1-2.1-sdk AS builder

ADD .  /src

WORKDIR src

RUN  Cake --bootstrap && Cake
```
